# Default joint positions for mock hardware startup.

left:
  shoulder_pan_joint: 0.888692
  shoulder_lift_joint: -1.79769
  elbow_joint: -2.04204
  wrist_1_joint: 3.83972
  wrist_2_joint: -1.8326
  wrist_3_joint: 1.57
  # gripper_joint: 0.4

right:
  shoulder_pan_joint: -0.888692
  shoulder_lift_joint: -1.36136
  elbow_joint: 2.04204
  wrist_1_joint: -0.698132
  wrist_2_joint: 1.8326
  wrist_3_joint: -1.57
  # gripper_joint: 0.4
